version: "2"
services:
    boilerplate-api:
        build: .
        environment:
            - MONGO_URI=mongodb://mongodb:27017/node-restapi-boilerplate
        volumes:
            - .:/app
        ports:
            - "8080:8080"
        depends_on:
            - mongodb

    mongodb:
        image: mongo
        ports:
            - "27017:27017"
